"""empty message

Revision ID: 4033bf20b748
Revises: 7fa611714908
Create Date: 2026-02-04 03:33:33.744532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4033bf20b748'
down_revision: Union[str, Sequence[str], None] = '7fa611714908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction', sa.Column('top_bidder_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_auction_top_bidder_id'), 'auction', ['top_bidder_id'], unique=False)
    op.create_foreign_key(None, 'auction', 'user', ['top_bidder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auction', type_='foreignkey')
    op.drop_index(op.f('ix_auction_top_bidder_id'), table_name='auction')
    op.drop_column('auction', 'top_bidder_id')
    # ### end Alembic commands ###
